djangoPortfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("portfolio.urls"))
]

portfolio/urls.py
from django.urls import path

from . import views
app_name = "portfolio"
urlpatterns = [
    path('', views.Home, name="home"),
    path('about/', views.About, name="about"),
    path('contact/', views.Contact, name="contact"),
    path('languages/', views.Languages, name="languages"),
    path('services/', views.Services, name="services")
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render

# Create your views here.

def Home(request):
    return render(request, 'home.html')

def About(request):
    return render(request, 'about.html')

def Languages(request):
    return render(request, 'languages.html')
def Contact(request):
    return render(request, 'contact.html')

def Services(request):
    return render(request, 'services.html')

portfolio/templates/about.html
{% extends 'layout.html' %}
{% block body %}
	<section id="about" class="container">
    <h2>About Me</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto asperiores consectetur dolores, enim error est molestiae nam natus,
        nihil placeat, recusandae suscipit ullam voluptates. Debitis mollitia nostrum temporibus voluptate voluptatem!</p>
</section>
{% endblock %}

portfolio/templates/contact.html
{% extends 'layout.html' %}
{% block body %}
	<section id="contact" class="container bg-light py-5">
    <h2 class="text-center">Contact</h2>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d127648.30582652555!2d37.0132762!3d-1.1536634000000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f38a78cb4e50d%3A0xdaa7fad9c2cbf0fb!2sRuiru!5e0!3m2!1sen!2ske!4v1697271657259!5m2!1sen!2ske" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <div id="map"></div>
        </div>
        <div class="col-md-6 mx-auto">
           <div class="contact-form">
                <form>
                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" id="name" placeholder="Enter your name">
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" id="email" placeholder="Enter your email">
                    </div>
                    <div class="form-group">
                        <label for="message">Message:</label>
                        <textarea class="form-control" id="message" rows="5" placeholder="Type your message"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
	<section id="home">
    <div id="carousel-container" class="container-fluid">
        <!-- Add your slider content here -->
        <div id="carouselExample" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'images/image1.jpg' %}" class="d-block w-100" alt="Slide 1">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/image2.jpg' %}" class="d-block w-100" alt="Slide 2">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/image3.jpg' %}" class="d-block w-100" alt="Slide 3">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</section>
{% endblock %}

portfolio/templates/languages.html
{% extends 'layout.html' %}
{% block body %}
	<section id="languages" class="container">
    <h2>Languages</h2>
    <ul>
        <li>Python</li>
        <li>JavaScript</li>
        <li>HTML</li>
        <li>CSS</li>
    </ul>
</section>
{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a class="navbar-brand" href="#">PP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'portfolio:home' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'portfolio:about' %}">About</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'portfolio:languages' %}">Languages</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'portfolio:services' %}">Services</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'portfolio:contact' %}">Contact</a></li>
        </ul>
    </div>
</nav>
{% block body %}

{% endblock %}
<footer class="bg-dark text-light text-center p-3">
    <p> 2023 Prisha Patel. All Rights Reserved.</p>
</footer>
</body>
</html>

portfolio/templates/services.html
{% extends 'layout.html' %}
{% block body %}
	<section id="services" class="container">
    <h2>Services</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae culpa cupiditate exercitationem magnam maiores nisi quisquam? Fuga nam, neque omnis pariatur rem repellat similique! Aspernatur debitis minima natus quibusdam. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem, dicta dolorum facere facilis fuga illo, illum libero porro possimus qui saepe soluta sunt voluptates.
        Iure nam quibusdam quis tenetur velit!</p>
</section>
{% endblock %}